#!/bin/sh /etc/rc.common

# shellcheck disable=SC2034
USE_PROCD=1
START=99

prog_name="iperf3"
bin="/usr/bin/$prog_name"

start_service() {
    procd_open_instance
    procd_set_param command "$bin" -s
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
