#!/usr/bin/env python3
import sys

sys.dont_write_bytecode = True
from pathlib import Path

try:
    from .common import *
    from .downloads import download_text_lines as curl_download_text_lines
    from .generate_server_runtime import shell_quote
    from .tunnel_model import exit_route_env_key
except ImportError:
    from common import *  # type: ignore
    from downloads import download_text_lines as curl_download_text_lines  # type: ignore
    from generate_server_runtime import shell_quote  # type: ignore
    from tunnel_model import exit_route_env_key  # type: ignore


def normalize_ipset_lines(lines: list[str]) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()

    for line in lines:
        item = line.strip()

        if not item or item.startswith("#"):
            continue

        if item in seen:
            continue

        seen.add(item)
        out.append(item)

    return out


def download_text_lines(url: str) -> list[str]:
    return [
        line
        for line in curl_download_text_lines(url)
        if line and not line.startswith("#")
    ]


def direct_country_url(country: str) -> str:
    return f"{URL_IPVERSE_RIR}/country/{country}/ipv4-aggregated.txt"


def direct_asn_url(asn: str) -> str:
    return f"{URL_IPVERSE_ASN}/as/{asn}/ipv4-aggregated.txt"


def direct_static_lines(cfg: ConfigData) -> list[str]:
    lines: list[str] = []

    lines.extend(LOCAL_DIRECT_IPSETS)
    lines.extend(cfg.exit_direct.subnets)

    for hub in cfg.mesh_hubs:
        lines.append(hub.listen_ip)

    for hub in cfg.exit_hubs:
        if hub.listen_ip:
            lines.append(hub.listen_ip)
        if hub.exit_ip:
            lines.append(hub.exit_ip)

    return normalize_ipset_lines(lines)


def direct_dynamic_lines(cfg: ConfigData) -> list[str]:
    lines: list[str] = []

    for country in cfg.exit_direct.countries:
        lines.extend(download_text_lines(direct_country_url(country)))

    for asn in cfg.exit_direct.asns:
        lines.extend(download_text_lines(direct_asn_url(asn)))

    return normalize_ipset_lines(lines)


def build_direct_ipset_lines(
    cfg: ConfigData,
    *,
    skip_dynamic_downloads: bool = False,
) -> tuple[list[str], list[str]]:
    static_lines = direct_static_lines(cfg)
    dynamic_lines = [] if skip_dynamic_downloads else direct_dynamic_lines(cfg)
    direct_lines = normalize_ipset_lines(static_lines + dynamic_lines)
    return static_lines, direct_lines


def build_runtime_env(cfg: ConfigData, router_name: str | None = None) -> str:
    hubs = (
        router_exit_order_hubs(cfg, router_name)
        if router_name is not None
        else [cfg.exit_hubs_by_name[name] for name in cfg.exit_order]
    )
    target_names = []
    for hub in hubs:
        key = exit_route_env_key(hub.name)
        iface = router_exit_ipip_iface_name(hub.name)
        expected_iface = f"ip{hub.name}"
        if key != hub.name or iface != expected_iface:
            die(
                f"exit hub {hub.name!r} cannot be used as an exit-route target; "
                "use a short uppercase ASCII name containing A-Z, 0-9 or _ so the IPIP interface "
                f"is {expected_iface!r}"
            )
        target_names.append(hub.name)

    values = {
        "IPSETS_DIR": RUNTIME_IPSETS_DIR,
        "STATIC_DIRECT_NAME": RUNTIME_DIRECT_STATIC_NAME,
        "OUT_DIRECT_NAME": RUNTIME_DIRECT_OUT_NAME,
        "DIRECT_COUNTRIES": " ".join(cfg.exit_direct.countries),
        "DIRECT_ASNS": " ".join(cfg.exit_direct.asns),
        "CHECK_DOH_DOMAIN": CHECK_DOH_DOMAIN,
        "CHECK_DOH_INTERVAL": str(CHECK_DOH_INTERVAL),
        "CHECK_DOH_RESOLV": CHECK_DOH_RESOLV,
        "CHECK_DOH_RESOLV_WAIT_MAX": str(CHECK_DOH_RESOLV_WAIT_MAX),
        "CHECK_DOH_PROVIDER_DOMAINS": " ".join(CHECK_DOH_PROVIDER_DOMAINS),
        "EXIT_ROUTE_TABLE": str(EXIT_ROUTE_TABLE),
        "EXIT_ROUTE_INTERVAL": str(EXIT_ROUTE_INTERVAL),
        "UPDATE_IPSETS_CURL_CONNECT_TIMEOUT": str(UPDATE_IPSETS_CURL_CONNECT_TIMEOUT),
        "UPDATE_IPSETS_CURL_MAX_TIME": str(UPDATE_IPSETS_CURL_MAX_TIME),
        "UPDATE_IPSETS_CURL_RETRY": str(UPDATE_IPSETS_CURL_RETRY),
        "EXIT_ROUTE_TARGETS": " ".join(target_names),
    }

    lines = [
        "# Generated by generate.py. Do not edit on the host.",
        "# Runtime settings consumed by /etc/scripts/*.sh.",
    ]
    lines.extend(f"{key}={shell_quote(value)}" for key, value in values.items())

    for hub in hubs:
        key = exit_route_env_key(hub.name)
        lines.append(
            f"EXIT_ROUTE_{key}_PREFIX={shell_quote(str(exit_announce_network(hub)))}"
        )

    lines.append("")
    return "\n".join(lines)


def write_ipsets_at(
    root: Path,
    cfg: ConfigData,
    router_name: str | None = None,
    *,
    static_lines: list[str] | None = None,
    direct_lines: list[str] | None = None,
) -> None:
    if static_lines is None or direct_lines is None:
        static_lines, direct_lines = build_direct_ipset_lines(cfg)

    write(root / REL_DIRECT_STATIC_IPSET, "\n".join(static_lines) + "\n")
    write(root / REL_RUNTIME_ENV, build_runtime_env(cfg, router_name))
    write(root / REL_DIRECT_IPSET, "\n".join(direct_lines) + "\n")


def write_router_ipsets(
    cfg: ConfigData,
    router_name: str,
    *,
    static_lines: list[str] | None = None,
    direct_lines: list[str] | None = None,
) -> None:
    write_ipsets_at(
        router_dir(cfg, router_name),
        cfg,
        router_name,
        static_lines=static_lines,
        direct_lines=direct_lines,
    )


def write_server_ipsets(
    cfg: ConfigData,
    exit_name: str,
    *,
    static_lines: list[str] | None = None,
    direct_lines: list[str] | None = None,
) -> None:
    if static_lines is None or direct_lines is None:
        static_lines, direct_lines = build_direct_ipset_lines(cfg)

    write(
        server_path(exit_name, "etc", "ipsets", "direct-static.txt"),
        "\n".join(static_lines) + "\n",
    )
    write(
        server_path(exit_name, "etc", "ipsets", "direct.txt"),
        "\n".join(direct_lines) + "\n",
    )
